# Generated by Django 5.2.4 on 2025-08-03 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_prueba_taller_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
