# Generated by Django 5.2.4 on 2025-08-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0006_alter_curso_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_access', to='authtoken.token')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso')),
            ],
        ),
    ]
