# Generated by Django 5.2.5 on 2025-08-08 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_videoaccesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='plantilla_calificacion',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='archivo_xml',
            field=models.FileField(upload_to='pruebas/xml/'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AttentionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attention_percentage', models.FloatField()),
                ('attention_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_results', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attention_results', to='users.taller')),
                ('video', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attention_results', to='users.video')),
            ],
            options={
                'verbose_name': 'Resultado de atención',
                'verbose_name_plural': 'Resultados de atención',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('porcentaje', models.FloatField()),
                ('respuestas', models.JSONField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.prueba')),
            ],
            options={
                'verbose_name': 'Resultado de Prueba',
                'verbose_name_plural': 'Resultados de Pruebas',
            },
        ),
        migrations.CreateModel(
            name='TallerEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='talleres_enviados/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.taller')),
            ],
            options={
                'verbose_name': 'Taller enviado',
                'verbose_name_plural': 'Talleres enviados',
            },
        ),
        migrations.CreateModel(
            name='VideoAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attention_percentage', models.FloatField()),
                ('attention_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.video')),
            ],
            options={
                'verbose_name': 'Registro de atención a video',
                'verbose_name_plural': 'Registros de atención a videos',
            },
        ),
    ]
