# Generated by Django 5.2.5 on 2025-08-08 23:57

from django.db import migrations, models
import json

def cambiar_xml_a_json(apps, schema_editor):
    Prueba = apps.get_model('users', 'Prueba')
    
    # Renombrar archivo_xml a archivo_json
    for prueba in Prueba.objects.all():
        if prueba.archivo_xml:
            prueba.archivo_json = prueba.archivo_xml
            prueba.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_video_options_and_more'),  # Reemplaza 000X con el número correcto
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='archivo_xml',
            new_name='archivo_json',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='archivo_json',
            field=models.FileField(upload_to='pruebas/json/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='json_content',
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.RunPython(cambiar_xml_a_json),
    ]
