# Generated by Django 5.2.5 on 2025-08-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cambiar_xml_a_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='archivo_json',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='json_content',
        ),
        migrations.AddField(
            model_name='prueba',
            name='archivo_xml',
            field=models.FileField(default='', upload_to='pruebas/xml/'),
            preserve_default=False,
        ),
    ]
