# Generated by Django 5.2.5 on 2025-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cambiar_xml_a_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoprueba',
            name='porcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
