# Generated by Django 5.2.5 on 2025-08-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_resultadoprueba_porcentaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoprueba',
            old_name='respuestas',
            new_name='respuesta',
        ),
    ]
