# Generated by Django 5.2.5 on 2025-08-10 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_resultadoprueba_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='resultados_atencion',
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_prueba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='users.prueba'),
        ),
    ]
