# Generated by Django 5.2.5 on 2025-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_resultadoprueba_resultados_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerenviado',
            name='respuesta',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
