# Generated by Django 5.2.5 on 2025-08-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_tallerenviado_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoaccesstoken',
            options={},
        ),
    ]
