# Generated by Django 5.2.5 on 2025-08-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20250811_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoaccesstoken',
            options={'verbose_name': 'Token de acceso a video', 'verbose_name_plural': 'Tokens de acceso a videos'},
        ),
    ]
