# Generated by Django 5.2.5 on 2025-08-13 21:23

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_videoaccesstoken_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaccesstoken',
            name='token',
        ),
        migrations.AddField(
            model_name='videoaccesstoken',
            name='token_key',
            field=models.CharField(default=users.models.default_token, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='videoaccesstoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoaccesstoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videoaccesstoken',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='users.video'),
        ),
    ]
